#import:
#  - /path/to/alacritty.yml

window:
  padding:
    x: 32
    y: 32
 
  opacity: 1.0
  
  title: AraAratty
  dynamic_title: true

  history: 5000

font:
  normal:
    Default:
    family: azukifontB
    style: Regular

  bold:
    family: azukifontB
    style: Bold
  
  italic:
    family: azukifontB
    style: Bold
  
  size: 7.5

colors:
  primary:
    background: '#5a5475'
    foreground: '#f8f8f2'
    
  normal:
    black:   '#b29cc8'
    red:     '#ffb7d1'
    green:   '#c0ffde'
    yellow:  '#ffee99'
    blue:    '#b29cc8'
    magenta: '#ffb7d1'
    cyan:    '#c0ffde'
    white:   '#ffee99'

  bright:
    black:   '#b29cc8'
    red:     '#ffb7d1'
    green:   '#c0ffde'
    yellow:  '#ffee99'
    blue:    '#b29cc8'
    magenta: '#ffb7d1'
    cyan:    '#c0ffde'
    white:   '#ffee99'


